Repository stfc/cloud-deployed-apps, pull requests merged in 2024-06, with the labels that each got.

#77 Switch to subchart
  charts/dev/argocd/values.yaml
  charts/dev/capi-infra/Chart.yaml
  charts/dev/capi-infra/requirements.yaml
  charts/dev/capi-infra/values.yaml
  clusters/dev/management/apps.yaml
  secrets/dev/management/api-server-fip.yaml
  secrets/dev/management/app-creds.yaml
Labels: enhancement

#83 DEPLOY: Add a dev cluster for Jupyterhub
  clusters/dev/test-jupyter/infra-values.yaml
  secrets/dev/test-jupyter/.sops.yaml
  secrets/dev/test-jupyter/api-server-fip.yaml
  secrets/dev/test-jupyter/app-creds.yaml
Labels: deployment

#87 DEPLOY: Add a david-test cluster
  clusters/dev/david-jhub/infra-values.yaml
  secrets/dev/david-jhub/.sops.yaml
  secrets/dev/david-jhub/api-server-fip.yaml
  secrets/dev/david-jhub/app-creds.yaml
Labels: deployment

#90 DOC: Update docs on deploying clusters
  docs/child-clusters.md
  docs/clusters.md
Labels: documentation

#89 Fix appset invalid preserve
  clusters/dev/management/apps.yaml
Labels: bug

#91 Script fixes for secret and initial deployment
  scripts/bootstrap_yaml/argocd-ns.yaml
  scripts/deploy-helm-secret.sh
  scripts/deploy.sh
Labels: bug

#94 Add staging charts
  charts/staging/argocd/Chart.yaml
  charts/staging/argocd/requirements.yaml
  charts/staging/argocd/values.yaml
  charts/staging/capi-infra/Chart.yaml
  charts/staging/capi-infra/requirements.yaml
  charts/staging/capi-infra/values.yaml
  charts/staging/cert-manager/Chart.yaml
  charts/staging/cert-manager/requirements.yaml
  charts/staging/cert-manager/templates/le-prod-clusterissuer.yaml
  charts/staging/cert-manager/templates/le-staging-clusterissuer.yaml
  charts/staging/cert-manager/templates/self-signed-clusterissuer.yaml
  charts/staging/cert-manager/values.yaml
  charts/staging/cluster-api-addon-provider/Chart.yaml
  charts/staging/cluster-api-addon-provider/requirements.yaml
  charts/staging/cluster-api-addon-provider/values.yaml
  charts/staging/longhorn/Chart.yaml
  charts/staging/longhorn/requirements.yaml
  charts/staging/longhorn/values.yaml
Labels: enhancement

#93 Add a staging environment
  clusters/staging/management/apps.yaml
  clusters/staging/management/argocd-setup-values.yaml
  clusters/staging/management/infra-values.yaml
  secrets/staging/management/.sops.yaml
  secrets/staging/management/api-server-fip.yaml
  secrets/staging/management/app-creds.yaml
Labels: enhancement

#92 DOC: Reformatting of documentation
  README.md
  docs/README.md
  docs/app-setup.md
  docs/child-clusters.md
  docs/clusters.md
  docs/deploying-apps.md
  docs/infra-setup.md
Labels: documentation

#96 Staging deployment
  clusters/staging/management/apps.yaml
  secrets/staging/management/api-server-fip.yaml
  secrets/staging/management/app-creds.yaml
Labels: deployment
