Repository stfc/cloud-deployed-apps, pull requests merged in 2024-10, with the labels that each got.

#173 BUG: use crds.enable=true
  charts/staging/cert-manager/values.yaml
Labels: bug

#187 BUG: disable galaxy
  clusters/dev/galaxy/apps.yaml
Labels: deployment

#201 Bump infra values for CAPI infra
  charts/dev/capi-infra/Chart.yaml
  charts/dev/cluster-api-addon-provider/Chart.yaml
Labels: enhancement

#202 Update ingress IPs and DNS entries for prod clusters
  clusters/prod/management/infra-values.yaml
  clusters/prod/worker/infra-values.yaml
Labels: enhancement

#205 BUG: Point staging worker to another kubeapi FIP
  secrets/staging/worker/api-server-fip.yaml
Labels: bug

#204 Promote latest CAPI infra to prod
  charts/dev/capi-infra/values.yaml
  charts/prod/capi-infra/Chart.yaml
  charts/prod/capi-infra/values.yaml
  charts/prod/cluster-api-addon-provider/Chart.yaml
  charts/staging/capi-infra/values.yaml
  clusters/prod/management/infra-values.yaml
  clusters/prod/worker/infra-values.yaml
Labels: enhancement
