Repository stfc/cloud-deployed-apps, pull requests merged in 2024-11, with the labels that each got.

#206 Pull latest version of ArgoCD for AppSet bug fix
  charts/dev/argocd/Chart.yaml
  charts/staging/argocd/Chart.yaml
  charts/staging/argocd/requirements.yaml
Labels: bug

#207 MAINT: Promote latest argocd to prod
  charts/prod/argocd/Chart.yaml
  charts/prod/argocd/requirements.yaml
Labels: bug, deployment

#208 Misc fixes across deployed clusters
  charts/prod/capi-infra/requirements.yaml
  charts/prod/cluster-api-addon-provider/requirements.yaml
  clusters/dev/management/infra-values.yaml
  clusters/staging/management/infra-values.yaml
Labels: bug

#209 MAINT: Bump CAPI image and version on dev
  charts/dev/capi-infra/Chart.yaml
  charts/dev/capi-infra/values.yaml
Labels: deployment

#212 MAINT: Drop DaveW cluster
  clusters/dev/davew/infra-values.yaml
Labels: deployment

#217 [DEPLOYMENT] Scale up worker nodes
  clusters/staging/worker/infra-values.yaml
Labels: deployment

#218 DEPLOY: Deploying test cluster for Longhorn issue.
  clusters/dev/rwhiting/apps.yaml
  clusters/dev/rwhiting/argocd-setup-values.yaml
  clusters/dev/rwhiting/infra-values.yaml
  secrets/dev/rwhiting/.sops.yaml
  secrets/dev/rwhiting/api-server-fip.yaml
  secrets/dev/rwhiting/app-cred.yaml
Labels: deployment
