Repository stfc/cloud-deployed-apps, pull requests merged in 2024-12, with the labels that each got.

#236 Update secrets.md
  docs/secrets.md
Labels: documentation

#231 ENH: Add chatops to dev
  .gitignore
  charts/dev/chatops/Chart.yaml
  charts/dev/chatops/secrets-templates/secrets.yaml
  charts/dev/chatops/templates/cloud-chatops.yaml
  charts/dev/chatops/templates/config-map.yaml
  charts/dev/chatops/templates/secrets.yaml
  charts/dev/chatops/values.yaml
  clusters/dev/worker/apps.yaml
  docs/apps/chatops.md
  secrets/dev/worker/apps/chatops.yaml
Labels: deployment

#239 BUG: Fix helm templating for ChatOps deployment
  charts/dev/chatops/secrets-templates/secrets.yaml
  charts/dev/chatops/templates/cloud-chatops.yaml
  charts/dev/chatops/templates/config-map.yaml
  charts/dev/chatops/templates/secrets.yaml
  charts/dev/chatops/values.yaml
  secrets/dev/worker/apps/chatops.yaml
Labels: bug

#241 ENH: Add new cluster for cloud chatops
  clusters/dev/cloud-chatops/infra-values.yaml
  secrets/dev/cloud-chatops/infra/.sops.yaml
  secrets/dev/cloud-chatops/infra/api-server-fip.yaml
  secrets/dev/cloud-chatops/infra/app-creds.yaml
Labels: deployment

#242 Update to v5
  charts/dev/chatops/Chart.yaml
  charts/dev/chatops/templates/cloud-chatops.yaml
  charts/dev/chatops/templates/config-map.yaml
  charts/dev/chatops/values.yaml
Labels: enhancement

#244 DEPLOY: Added test harbor cluster
  clusters/dev/harbor/infra-values.yaml
  secrets/dev/harbor/infra/.sops.yaml
  secrets/dev/harbor/infra/api-server-fip.yaml
  secrets/dev/harbor/infra/app-creds.yaml
Labels: deployment

#238 BUG: Alertmanager fixes
  charts/dev/capi-infra/values.yaml
  clusters/dev/worker/infra-values.yaml
Labels: bug
