Repository stfc/cloud-deployed-apps, pull requests merged in 2025-01, with the labels that each got.

#250 Edit chatops setup values
  clusters/dev/cloud-chatops/apps.yaml
  clusters/dev/cloud-chatops/argocd-setup-values.yaml
  clusters/dev/cloud-chatops/infra-values.yaml
Labels: bug

#253 MAINT: Move cluster App of Apps to feature branch
  clusters/dev/cloud-chatops/apps.yaml
Labels: bug

#254 Dev cloud chatops
  charts/dev/chatops/values.yaml
  secrets/dev/cloud-chatops/apps/chatops.yaml
Labels: bug

#258 ENH: Add repo to list
  charts/dev/chatops/values.yaml
Labels: enhancement

#261 Bug: Fix longhorn settings
  charts/dev/longhorn/values.yaml
Labels: bug, enhancement

#266 MAINT: Renew cluster application credentials
  secrets/dev/cloud-chatops/infra/app-creds.yaml
Labels: bug

#270 MAINT: Rotate GitHub PAT token to Cloud account
  secrets/staging/worker/apps/chatops.yaml
Labels: deployment

#265 ENH: Add more cloud members to the values
  secrets/staging/worker/apps/chatops.yaml
Labels: enhancement
